Fix/social media handle
edustipend/dotorg pull request #106
Opened 2024-01-13 20:02 UTC by RB-Isiaq

> Added the social media handle key to the user payload

2024-01-13 21:08 UTC, edustipend-root commented on src/components/ApplicationSteps/Step5Application/Internals/EmailVerified/EmailVerified.jsx
> +        setTimeout(() => {
What does this change do?

2024-01-13 21:09 UTC, edustipend-root requested changes
Update the social media handle to reflect whatever the user selects.

2024-01-13 21:09 UTC, edustipend-root commented on src/components/ApplicationSteps/Step5Application/Internals/Submit/Submit.jsx
> +      twitter: twitterHandle
@RB-Isiaq, we should be sending whatever the user selects. If they picked Facebook this should be `facebook` not `twitter`, correct?

2024-01-14 05:56 UTC, RB-Isiaq commented on src/components/ApplicationSteps/Step5Application/Internals/Submit/Submit.jsx
> +      twitter: twitterHandle
![image](https://github.com/edustipend/dotorg/assets/99425435/46abd3d7-8f5d-419b-bd46-a07c150ed566)
We actually have this on the frontend, it's only a twitter handle field

2024-01-14 06:02 UTC, RB-Isiaq commented on src/components/ApplicationSteps/Step5Application/Internals/EmailVerified/EmailVerified.jsx
> +        setTimeout(() => {
After a successful email verification, the emailVerification state is changed to true, and the user state is set to the decoded information from the token, thereby storing and persisting the userInfo to localstorage.

The nav(0) refreshes the page, and navigates the user to the welcome page, if authenticated.

2024-01-14 06:04 UTC, RB-Isiaq commented on src/components/ApplicationSteps/Step5Application/Internals/Submit/Submit.jsx
> +      twitter: twitterHandle
![image](https://github.com/edustipend/dotorg/assets/99425435/cc699a36-81a5-4757-bfac-d44fe2ddc87a)

2024-01-14 07:07 UTC, RB-Isiaq commented on src/components/ApplicationSteps/Step5Application/Internals/Submit/Submit.jsx
> +      twitter: twitterHandle
Made some changes, to allow users select and insert their handles

![Screenshot 2024-01-14 075641](https://github.com/edustipend/dotorg/assets/99425435/69eaed65-7b66-4858-95e5-91862e99ce67)
![Screenshot 2024-01-14 075717](https://github.com/edustipend/dotorg/assets/99425435/9174aef1-f514-4f1a-86b4-38b7be72f847)
![Screenshot 2024-01-14 080414](https://github.com/edustipend/dotorg/assets/99425435/f880ed04-63db-4450-9040-a888cc05729c)

2024-01-14 07:29 UTC, edustipend-root commented on src/components/ApplicationSteps/Step5Application/Internals/Submit/Submit.jsx
> +      twitter: twitterHandle
Thanks for making this change @RB-Isiaq

2024-01-14 07:29 UTC, merged