Feature/donate-now-hero-section
edustipend/dotorg pull request #133
Opened 2024-02-07 12:58 UTC by misspelz

Work in Progress
![image](https://github.com/edustipend/dotorg/assets/99533069/46544c6e-e38e-4695-9f91-ac4159d69e8d)
![image](https://github.com/edustipend/dotorg/assets/99533069/dee41fb3-fbab-41c9-a402-8f75b7eaa23f)

2024-02-14 10:38 UTC, edustipend-root requested changes
Great work @misspelz! Thank you for this
Added a few comments, please make the minor changes so I can get this merged in.

2024-02-14 23:47 UTC, misspelz commented on src/assets/ade.png
Deleted

2024-02-14 23:54 UTC, misspelz commented on src/assets/habby.png
Done

2024-02-14 23:55 UTC, misspelz commented on src/pages/support-a-learner/SupportALearner.module.css
Deleted

2024-02-15 00:04 UTC, misspelz commented on src/sections/SupportALearner/HeroSection/HeroSection.jsx
> +  const quotesArray = [
I have moved it to the constant file

2024-02-15 00:05 UTC, misspelz commented on src/sections/SupportALearner/HeroSection/contants.js
I have moved an array of the beneficiaries

2024-02-15 00:06 UTC, misspelz commented on src/sections/SupportALearner/HeroSection/HeroSection.jsx
> +    <main  className={styles.bg}>
Okay, understood
I have used div

2024-02-15 00:13 UTC, misspelz commented on src/sections/SupportALearner/HeroSection/HeroSection.jsx
> +        "I didn't have sufficient data to pull through the duration of my course, but Edustipend came to my rescue. And now I made it to the final stage, where my team and I organized clean up progra
I have pasted the right one

2024-02-15 00:14 UTC, misspelz commented on src/sections/SupportALearner/HeroSection/HeroSection.jsx
> +        "The laptop stipend was a huge help to me during my final year at the university when I was working on my research project. The Bank of America Investment Banking virtual experience program o
Updated

2024-02-15 00:17 UTC, misspelz commented on src/sections/SupportALearner/HeroSection/HeroSection.jsx
> +      author: 'Isaac Etor',
Yes
I just informed Joshua.
He will get it across to me

2024-02-22 08:56 UTC, edustipend-root commented on src/sections/SupportALearner/HeroSection/__tests__/HeroSection.test.js
> +  /**
Let's pick this up in a separate PR.

2024-02-22 08:57 UTC, edustipend-root commented on src/sections/SupportALearner/HeroSection/contants.js
> +      'Edustispend supported my career advancement by assisting with a portion of my course fees, thereby providing vital financial support and facilitating my pursuit of educational objectives. Thei
There's a typo here: `Edustipend` not `Edustispend`

2024-02-22 09:01 UTC, edustipend-root approved these changes
@misspelz, I'm approve this for now so we can get it merged in but we need to make some changes in a follow-up PR:

- We need to update the quote component on the image such that when user hovers over the text, it shows the full text because right now the text is blocking the image especially on mobile. Let me know if this makes sense to you.
- 
- The typo change

2024-02-22 09:02 UTC, merged

2024-02-23 00:47 UTC, 2gedareactfrontend commented on src/sections/SupportALearner/HeroSection/contants.js
> +      'Edustispend supported my career advancement by assisting with a portion of my course fees, thereby providing vital financial support and facilitating my pursuit of educational objectives. Thei
Corrected

2024-02-23 00:47 UTC, 2gedareactfrontend commented on src/sections/SupportALearner/HeroSection/__tests__/HeroSection.test.js
> +  /**
Okay

2024-02-23 00:49 UTC, 2gedareactfrontend commented
> @misspelz, I'm approve this for now so we can get it merged in but we need to make some changes in a follow-up PR:
> 
> * We need to update the quote component on the image such that when user hovers over the text, it shows the full text because right now the text is blocking the image especially on mobile. Let me know if this makes sense to you.
> * The typo change

I understand but what about the mobile view? Will users be able to hover ?