Feat/donate now form
edustipend/dotorg pull request #136
Opened 2024-02-09 12:04 UTC by Ezeh20

This PR holds the donation range picker and the donation form
The range picker component can be found in story book

[Jam Video - https-__twitter.com_intent_tweet-text=Hey! I just donated to Edustipend, supporting education for all. 📚💙 Join me in making a difference! Click the link to donate. 🌟 #Edustipend https-__www.edustipend.or.webm](https://github.com/edustipend/dotorg/assets/29344226/db99a71d-1494-4c4e-a4b9-ab08f5180124)

![Screenshot (380)](https://github.com/edustipend/dotorg/assets/29344226/3fbad23f-69ce-49c9-b1bd-174b3a401952)
![Screenshot (381)](https://github.com/edustipend/dotorg/assets/29344226/3ce5c906-4032-4393-a667-c7324f1168e9)
![Screenshot (383)](https://github.com/edustipend/dotorg/assets/29344226/68f50054-d91a-4a88-adfd-c4abc66e3d38)
![Screenshot (382)](https://github.com/edustipend/dotorg/assets/29344226/5ec29442-116e-489a-aaad-ef6696158402)
![Screenshot (379)](https://github.com/edustipend/dotorg/assets/29344226/00e3e6ce-fba5-4cbd-ac68-8e90715e2a85)
![Screenshot (384)](https://github.com/edustipend/dotorg/assets/29344226/5665634d-85c6-4f6a-8c48-a9ad1bbf60e4)

2024-02-14 10:50 UTC, edustipend-root commented on src/assets/aisha.svg
@Ezeh20, I think @misspelz has already added this image as a part of her PR. You can delete this file.
Also, we might not be displaying the image of the beneficiary on the Donate Now form anymore.

2024-02-14 10:58 UTC, edustipend-root requested changes
Really good job @Ezeh20, thank you for this!
Just some minor comments, please take a look and make the changes so that we can get it merged in.

2024-02-14 10:58 UTC, edustipend-root commented on src/assets/donateScreen.svg
Please get in touch with Ubon to give you the updated image for this. We have removed the `Make another donation` link in the updated image.

2024-02-14 10:58 UTC, edustipend-root commented on src/pages/donate-now/DonateNow.jsx
> +      setAmount(value);
So if `e.target.value` is an empty string, we will set amount value to the empty string?
Let's check this logic again.

2024-02-14 10:58 UTC, edustipend-root commented on src/pages/donate-now/DonateNow.jsx
> +                  label="Email Address"
can we move this to a `constants` file. Same with the placeholder below.

2024-02-14 10:58 UTC, edustipend-root commented on src/pages/donate-now/constants.js
> +  aisha:
We don't need this copy again since we are no longer including the image of the beneficiary on the Donate Now form.

2024-02-14 10:58 UTC, edustipend-root commented on src/pages/donate-now/internals/transactionModal/TransactionModal.jsx
> +  console.log(setShareUI);
Remove console log

2024-02-14 10:58 UTC, edustipend-root commented on src/pages/donate-now/internals/transactionModal/TransactionModal.jsx
> +  handleTransactionModal: PropTypes.func,
What does this function do? If it is to open/close the modal, can we rename it to something more descriptive like `handleToggleTransactionModal`?

2024-02-14 10:58 UTC, edustipend-root commented on src/sections/SupportALearner/DonationRange/DonationRange.jsx
> +                  <p className={styles.sum}>₦{`${formattedNumber} can get ${4} Laptops for ${4} learners`}</p>
Please create a task on the Trello board for the change to make this text dynamic so we don't forget it @Ezeh20

2024-02-18 20:11 UTC, Ezeh20 commented on src/pages/donate-now/DonateNow.jsx
> +      setAmount(value);
I cleaned it up to this

```
  if (value >= 0 && value <= max) {
      setAmount(value);
    }
```
then set the button `disabled={amount < 1000}`

This way, the button is disabled if the amount is less than 1000 and the user can't enter more than 1million

2024-02-18 20:31 UTC, Ezeh20 commented on src/assets/aisha.svg
Alright, I will wait for the updated design as i don't know what to put there

2024-02-22 09:14 UTC, edustipend-root commented on src/components/Button/Button.jsx
> +  ${disabled ? 'disabled' : ''} ${effectAlt ? 'effectAlt' : ''} ${effectClass} `}>
What's `effectAlt` vs `effectClass`? What is the difference between both?

2024-02-22 09:16 UTC, edustipend-root commented on src/components/Footer/Footer.jsx
> +  if (isDonation) {
Let's update this logic to include `isDashboard` as well, so 

```
if (isDonation || isDashboard) { return } 
```

2024-02-22 09:19 UTC, edustipend-root commented on src/pages/donate-now/DonateNow.jsx
> +                  label="Email Address"
@Ezeh20, you didn't address this.

2024-02-22 09:19 UTC, edustipend-root commented on src/pages/donate-now/constants.js
> +  aisha:
@Ezeh20, did you address this?

2024-02-22 09:20 UTC, edustipend-root commented on src/pages/donate-now/internals/transactionModal/TransactionModal.jsx
> +            label="Share on social media"
I would prefer for this labels to come from a constants.js file instead of hardcoding it.

2024-02-22 09:59 UTC, Ezeh20 commented on src/components/Footer/Footer.jsx
> +  if (isDonation) {
Alright

2024-02-22 10:04 UTC, Ezeh20 commented on src/components/Button/Button.jsx
> +  ${disabled ? 'disabled' : ''} ${effectAlt ? 'effectAlt' : ''} ${effectClass} `}>
The button styles in the design are not consistent, the button on the landing page has a big base while others has a smaller one, the effectAlt just toggles between them while the effectClass in general is there for optional custom styling.

2024-02-22 10:04 UTC, Ezeh20 commented on src/pages/donate-now/internals/transactionModal/TransactionModal.jsx
> +            label="Share on social media"
Alright

2024-02-22 10:06 UTC, Ezeh20 commented on src/pages/donate-now/constants.js
> +  aisha:
I am waiting for ubon's reply as regards to what I will put there if I remove the aisha content.

2024-02-22 10:06 UTC, Ezeh20 commented on src/pages/donate-now/DonateNow.jsx
> +                  label="Email Address"
I didn't just haven't pushed yet.

2024-02-28 10:48 UTC, edustipend-root commented
@Ezeh20, this PR has some merge conflicts. Please resolve so I can merge in.

2024-02-28 12:59 UTC, merged