How we select section
edustipend/dotorg pull request #137
Opened 2024-02-10 22:09 UTC by RB-Isiaq

> The how we select beneficiaries section

![Screenshot 2024-02-10 222501](https://github.com/edustipend/dotorg/assets/99425435/bd979605-5611-460a-9ca2-cf7f5a82d6a0)
![Screenshot 2024-02-10 222600](https://github.com/edustipend/dotorg/assets/99425435/a6dff5a7-2c4a-4515-b230-eb9dea14805d)
![Screenshot 2024-02-10 225135](https://github.com/edustipend/dotorg/assets/99425435/a0fa6eb5-8980-4da7-997d-3d9db4d0bddb)
![Screenshot 2024-02-10 225213](https://github.com/edustipend/dotorg/assets/99425435/ee175bf6-5639-4564-9d6d-141a5034c506)

2024-02-14 10:46 UTC, edustipend-root requested changes
Thanks for working on this @RB-Isiaq, just some minor changes that need to be made.

2024-02-14 10:46 UTC, edustipend-root commented on src/sections/SupportALearner/HowWeSelect/constants.js
> +      'Our vision is to support folks who really need a push with their lerning goals. As part of the application, you should show how you really need the stipend and how getting the stipend can help
Check the typo here @RB-Isiaq. 

"...how getting the stipend should be you **achieve** (not chieve) your learning goals."

2024-02-14 10:46 UTC, edustipend-root commented on src/sections/SupportALearner/HowWeSelect/constants.js
> +      'Everyone needs a laptop or data, we would like to see what they have achieved so far without the stipend . It could be a course or community you joined. We know it can be hard but the more you
Please pay attention to the text @RB-Isiaq - there are some spaces where there shouldn't be and missing periods. Please update it to:

"Everyone needs a laptop or data, we would like to see what they have achieved so far without the stipend. It could be a course you started or a community you joined. We know it can be hard but the more you can demonstrate progress despite the constraints, the better your chances."

2024-02-14 10:46 UTC, edustipend-root commented on src/sections/SupportALearner/HowWeSelect/constants.js
> +      'Everyone deserves a fair chance regardless of age, gender, state of origin, and we try to follow that, as much as possible. This means we will try to ensure that the stipends are evenly distri
Add period at the end of this.

2024-02-14 10:46 UTC, edustipend-root commented on src/sections/SupportALearner/HowWeSelect/constants.js
> +      'We do not ask for an entire epistle when asbpart of your application but we reall appreciate thoughtful responses. So answer all questions as descriptive yet concisely  as possible . Let your
Typo here again. Update it to:

"We do not ask for an entire epistle when completing your application but we really appreciate thoughtful responses. So answer all questions as descriptively yet concisely as possible. Let your personality show in your application."

2024-02-14 10:46 UTC, edustipend-root commented on src/sections/SupportALearner/HowWeSelect/constants.js
> +      'Core to our vision here at Edustipend is the idea of paying it forward. As part of the application, state how you plan to pay it forward if you get selected - how you plan to impact others as
Add a period at the end of this.

2024-02-14 11:19 UTC, RB-Isiaq commented on src/sections/SupportALearner/HowWeSelect/constants.js
> +      'Our vision is to support folks who really need a push with their lerning goals. As part of the application, you should show how you really need the stipend and how getting the stipend can help
Resolved.

2024-02-14 11:22 UTC, RB-Isiaq commented on src/sections/SupportALearner/HowWeSelect/constants.js
> +      'We do not ask for an entire epistle when asbpart of your application but we reall appreciate thoughtful responses. So answer all questions as descriptive yet concisely  as possible . Let your
My bad. I was just copying it directly from figma, I didn't really read through it then.
Resolved.

2024-02-22 09:04 UTC, edustipend-root commented
@RB-Isiaq, please resolve the merge conflicts here so I can approve so I can get it merged in.

2024-02-25 14:48 UTC, edustipend-root commented
More conflicts to be resolved here @RB-Isiaq

2024-02-27 13:57 UTC, RB-Isiaq commented
> More conflicts to be resolved here @RB-Isiaq

It has been resolved, please merge it in. @edustipend-root

2024-02-28 10:48 UTC, merged