Feat/testimonials section
edustipend/dotorg pull request #139
Opened 2024-02-22 12:56 UTC by Josh-Alhassan

2024-02-28 10:53 UTC, edustipend-root commented
@Josh-Alhassan, can you please add a video or screenshot of your UI changes so we can see.
Also there are some merge conflicts here that need to be resolved.

2024-02-28 12:27 UTC, Josh-Alhassan commented
https://drive.google.com/file/d/1xOxyHn1xQU2WMwuq5S8zMCqL1qokj0gu/view?usp=sharing

@edustipend-root here's a video record of the testimonial section

2024-05-20 10:02 UTC, edustipend-root commented on src/pages/support-a-learner/SupportALearner.module.css
> -  padding: 15px;
@Josh-Alhassan, why are we removing these?

2024-05-20 10:03 UTC, edustipend-root commented on src/pages/support-a-learner/SupportALearner.module.css
> +  /* padding: 15px; */
@Josh-Alhassan, why is this being added as comment? If we are not using it, we should take it out.

2024-05-20 10:04 UTC, edustipend-root commented on src/pages/support-a-learner/testimonial/Testimonial.jsx
> +  const testimonialsData = [
@Josh-Alhassan, please move this outside the function. It's static data that we don't need to be recreate every time the function is called.

2024-05-20 10:05 UTC, edustipend-root commented on src/pages/support-a-learner/testimonial/Testimonial.jsx
> +        <h2 className="testimonial__heading">Testimonials</h2>
@Josh-Alhassan, I'm very sure we already have a `Header` component built. Can we not use that here?

2024-05-20 10:06 UTC, edustipend-root commented on src/pages/support-a-learner/testimonial/Testimonial.jsx
> +  const infiniteTestimonialsData = [...testimonialsData, ...testimonialsData, ...testimonialsData];
What's the reasoning behind this? Also, a cleaner way to do this would be

`const infiniteTestimonialsData = Array(2).fill(testimonialsData)`

2024-05-20 10:07 UTC, edustipend-root requested changes
Thanks for these changes @Josh-Alhassan, looks good for the most part but please take note of the changes I asked that you make.

2024-05-23 17:00 UTC, Josh-Alhassan commented on src/pages/support-a-learner/SupportALearner.module.css
> -  padding: 15px;
It adds an extra space that is not needed.

2024-05-23 17:02 UTC, Josh-Alhassan commented on src/pages/support-a-learner/SupportALearner.module.css
> +  /* padding: 15px; */
@edustipend-root I have removed it

2024-05-23 17:04 UTC, Josh-Alhassan commented on src/pages/support-a-learner/testimonial/Testimonial.jsx
> +  const testimonialsData = [
@edustipend-root I have moved it testimonialsData array outside the function.

2024-05-24 11:36 UTC, Josh-Alhassan commented on src/pages/support-a-learner/testimonial/Testimonial.jsx
> +        <h2 className="testimonial__heading">Testimonials</h2>
@edustipend-root I have fixed this

2024-05-24 11:36 UTC, Josh-Alhassan commented on src/pages/support-a-learner/testimonial/Testimonial.jsx
> +  const infiniteTestimonialsData = [...testimonialsData, ...testimonialsData, ...testimonialsData];
@edustipend-root this didn't work as expected, but I have refactored the entire carousel code

2024-05-27 11:15 UTC, edustipend-root commented on src/components/Container/container.module.css
> +  /* margin-inline: 1.5rem; */
why is this commented out?

2024-05-27 11:16 UTC, edustipend-root commented on src/pages/support-a-learner/testimonial/TestimonialCard.css
> +  /* width: 100%;
Also, if we are not using these styles anymore, please remove them instead of commenting them out? @Josh-Alhassan

2024-05-29 21:56 UTC, Josh-Alhassan commented on src/components/Container/container.module.css
> +  /* margin-inline: 1.5rem; */
Done. Commented line removed.

2024-05-29 21:57 UTC, Josh-Alhassan commented on src/pages/support-a-learner/testimonial/TestimonialCard.css
> +  /* width: 100%;
@edustipend-root, done.

2024-05-29 21:57 UTC, Josh-Alhassan commented on src/components/Container/container.module.css
> +  /* margin-inline: 1.5rem; */
@edustipend-root

2024-05-29 22:01 UTC, Josh-Alhassan reviewed
Removed all comments @edustipend-root

2024-05-31 07:59 UTC, closed without merging