application window hook
edustipend/dotorg pull request #140
Opened 2024-02-22 21:47 UTC by RB-Isiaq

> The application window hook: needs the correct api route.
> Added an hover effect to the select options

![Screenshot 2024-02-22 223839](https://github.com/edustipend/dotorg/assets/99425435/d3b437a3-e841-4869-bacd-50a714b20228)

2024-02-25 13:37 UTC, edustipend-root requested changes
@RB-Isiaq, thanks so much for making this change.
Just a minor comment, please address it so we can merge it in.

2024-02-25 13:37 UTC, edustipend-root commented on src/hooks/useApplicationWindow.jsx
> +        toast.error(`Oops! Somethin went wrong. ${error.message}!`);
Please update the text here to `Unable to fetch application window status`

2024-02-27 14:09 UTC, RB-Isiaq commented
> @RB-Isiaq, thanks so much for making this change. Just a minor comment, please address it so we can merge it in.

Done @edustipend-root

2024-02-28 10:49 UTC, edustipend-root approved these changes

2024-02-28 10:49 UTC, merged