Feat/meet the team
edustipend/dotorg pull request #152
Opened 2024-05-08 10:17 UTC by Josh-Alhassan

![meet-the-team](https://github.com/edustipend/dotorg/assets/41088053/415c3516-2f05-4335-9211-754a2dd437cb)

Added meet the Team section

2024-05-20 10:21 UTC, edustipend-root commented on src/sections/MeetTheTeam/MeetTheTeam.jsx
> +            <div className="image-box box">
I would prefer we don't hardcode this instead we should have this read an array and render dynamically.

So something like

```
const teamMembers = [
  { name: 'Uduak', role: 'Founder', img: 'linkToImage'
]
```

And then you would render from the array dynamically.

2024-05-20 10:22 UTC, edustipend-root requested changes
@Josh-Alhassan, please review my comments.
Also, I didn't see any tests added to this PR.

2024-05-22 10:18 UTC, Josh-Alhassan commented on src/sections/MeetTheTeam/MeetTheTeam.jsx
> +            <div className="image-box box">
I refactored the code to read from an array and dynamically render.

2024-05-27 11:21 UTC, edustipend-root requested changes
@Josh-Alhassan, we have duplicate images which are not necessary. Please clean that up so I can get this merged in.

2024-05-27 11:21 UTC, edustipend-root commented on src/assets/Blessing.png
@Josh-Alhassan why do we have these assets here and also in the `team` folder? Similar to `Joshua.png` and `Uduak.png`.

What's the need for the duplicates?

2024-05-30 13:56 UTC, closed without merging