tests/about-us-mission-vision
edustipend/dotorg pull request #156
Opened 2024-05-10 15:04 UTC by misspelz

![image](https://github.com/edustipend/dotorg/assets/99533069/c2b5a8db-c225-4706-afbc-72444bba60cf)

2024-05-20 10:25 UTC, edustipend-root commented on src/sections/SupportALearner/LatestDonations/constants.js
> +export const donations = [
@misspelz, since this is mock data can we move this to a separate `donations.mock.ts` file?

2024-05-20 10:37 UTC, edustipend-root commented on src/sections/SupportALearner/Partners/Partners.jsx
> +const images = [...Array(6)].map((_, index) => require(`../../../assets/partner${index + 1}.svg`));
This is good @misspelz

2024-05-20 10:38 UTC, edustipend-root commented on yarn.lock
Please use `yarn` instead of `npm` when installing dependencies. We use `yarn` as our package manager.

2024-05-20 10:38 UTC, edustipend-root requested changes
This looks good @misspelz, thanks for making this change and adding tests.
Please address the comments I made so we can merge this in.

2024-05-20 22:06 UTC, misspelz commented on src/sections/SupportALearner/Partners/Partners.jsx
> +const images = [...Array(6)].map((_, index) => require(`../../../assets/partner${index + 1}.svg`));
Thank you

2024-05-20 22:07 UTC, misspelz commented on yarn.lock
Okay

2024-05-20 22:41 UTC, misspelz commented
> This looks good @misspelz, thanks for making this change and adding tests. Please address the comments I made so we can merge this in.



> This looks good @misspelz, thanks for making this change and adding tests. Please address the comments I made so we can merge this in.



> This looks good @misspelz, thanks for making this change and adding tests. Please address the comments I made so we can merge this in.

Done

2024-05-22 11:47 UTC, edustipend-root commented on src/sections/SupportALearner/LatestDonations/LatestDonations.jsx
> +    if (totalPages > 3) {
@misspelz, can we combine the logic here and on line 49?

2024-05-23 07:02 UTC, misspelz commented on src/sections/SupportALearner/LatestDonations/LatestDonations.jsx
> +    if (totalPages > 3) {
Done

2024-05-27 11:14 UTC, edustipend-root requested changes
Just one minor change before I can merge this in

2024-05-27 11:14 UTC, edustipend-root commented on yarn.lock
@misspelz, please remove the changes made in this `yarn.lock` file. The changes are showing that you used `npm` to install the dependencies instead of `yarn` and we only want to use `yarn` as our package manager.

2024-05-29 01:44 UTC, merged