Feature/donation flow
edustipend/dotorg pull request #159
Opened 2024-05-29 17:11 UTC by Ezeh20

https://github.com/edustipend/dotorg/assets/29344226/58d846cb-b954-48d2-98bd-b1b34114c913

This  PR contains the donation process :
 
- A user can click on the support a learner button in the support-a-learner page which will navigate the user to the donation form
- A user can also use the range picker to select a donation amount which ranges from 1,000 to 1,000,000.
- After filling the form, a user submits then a flutterwave link is returned by the server which is then used to redirect the user to flutterwave's checkout page.
- The user is finally redirected to edustipend with a status params then the appropriate modal is rendered.

2024-06-04 07:05 UTC, edustipend-root requested changes
This looks good @Ezeh20, but please look through my comments and address the small changes we need to improve this.

Thanks for the work!

2024-06-04 07:05 UTC, edustipend-root commented on src/pages/donate-now/DonateNow.jsx
> +    if (params.has('status')) {
What happens if `params` doesn't have `'status'`, I don't see any logic for the the `else` block of this condition

2024-06-04 07:05 UTC, edustipend-root commented on src/pages/donate-now/DonateNow.jsx
> +      } else if (status !== 'successful') {
nit: we can rewrite to just `else`, we don't need to add the `if` part since we already checked on line 94

2024-06-04 07:05 UTC, edustipend-root commented on src/pages/donate-now/DonateNow.jsx
> +    for (const key of params.keys()) {
Can you add a comment to explain why we are deleting the params?
Like a sample url with the params so anyone who reads this will know why we need to delete it.

2024-06-04 07:05 UTC, edustipend-root commented on src/pages/donate-now/DonateNow.jsx
> +  }, [handleFeedback]);
I believe we should add `params` to this dependencies list, right? So it should be:

```
  useEffect(() => {
    handleFeedback();
  }, [handleFeedback, params]);
```

2024-06-04 17:03 UTC, Ezeh20 commented on src/pages/donate-now/internals/transactionModal/TransactionModal.jsx
> +        <img src={close} alt={constants.close} className={`${styles.closeIcn} ${styles.closeIcn2}`} />
forgot to remove closeIcn2

2024-06-04 17:03 UTC, Ezeh20 commented on src/pages/donate-now/internals/transactionModal/TransactionModal.jsx
> +            // iconPosition={constants.right}
alright

2024-06-04 17:07 UTC, Ezeh20 commented on src/pages/donate-now/DonateNow.jsx
> +    <div className={styles.phoneInfo} onFocus={() => handleFocus(setUserData, focus)} onBlur={() => handleBlur(setUserData, focus)} tabIndex="0">
handleFocus and handleBlur  triggers the phone number tooltip when hover or clicked on both mobile and desktop

![kyc](https://github.com/edustipend/dotorg/assets/29344226/8d0c709b-f537-499e-9a7c-c9d12d6efc54)

2024-06-04 17:13 UTC, Ezeh20 commented on src/pages/donate-now/DonateNow.jsx
> +    if (params.has('status')) {
done

2024-06-04 17:20 UTC, Ezeh20 commented on src/pages/donate-now/DonateNow.jsx
> +    for (const key of params.keys()) {
done

2024-06-04 17:59 UTC, Ezeh20 commented on src/pages/donate-now/DonateNow.jsx
> +  }, [handleFeedback]);
we don't need the params in the useEffect dependencies list as the handleFeedback  useCallback function is already handling that

  const handleFeedback = useCallback(() => {
  .............................
    }, [params, setUserData, nav]);

2024-06-04 18:05 UTC, Ezeh20 commented on src/pages/donate-now/DonateNow.jsx
> +                  // disabled={!handleDisableButton && amount < 1000}
The handleDonation(); handles the submit action so we don't need to disable the button. We can give feedbacks as shown if the required fields are not filled.

![kyp](https://github.com/edustipend/dotorg/assets/29344226/2da6a207-b59f-4bd4-8da5-a0282366f259)

![fypo](https://github.com/edustipend/dotorg/assets/29344226/e89bb876-9fc5-4646-9fc6-ce088ad84307)

2024-06-05 11:51 UTC, edustipend-root commented on src/pages/donate-now/DonateNow.jsx
> +     * On success or On failure, flutterwave redirects the user to the specified route with two params attached
Thanks for adding this @Ezeh20!

2024-06-05 11:52 UTC, edustipend-root commented
@Ezeh20, there's a small merge conflict on your PR. Please resolve it so I can approve and merge this in

2024-06-06 10:21 UTC, edustipend-root approved these changes

2024-06-06 10:21 UTC, merged