Meet team
edustipend/dotorg pull request #160
Opened 2024-05-30 13:50 UTC by Josh-Alhassan

Had an unresolved conflict issue with meet-the-team branch. So I created a new pull request.

2024-05-30 14:04 UTC, Josh-Alhassan commented
![image](https://github.com/edustipend/dotorg/assets/41088053/817d1d4e-2e8f-4e53-8d37-b6191f080ed9)

2024-06-04 07:06 UTC, edustipend-root commented
@Josh-Alhassan, did you check to understand why this build is failing?

2024-06-04 07:08 UTC, edustipend-root requested changes
@Josh-Alhassan, thanks for the changes but the build is failing.
 
https://github.com/edustipend/dotorg/actions/runs/9303728767/job/25606692727?pr=160

Please see my comment on the PR.

2024-06-05 12:43 UTC, edustipend-root approved these changes

2024-06-05 12:43 UTC, merged