Feat/beneficiaries testimony
edustipend/dotorg pull request #161
Opened 2024-05-31 07:53 UTC by Josh-Alhassan

![image](https://github.com/edustipend/dotorg/assets/41088053/dc8f003f-ae8d-4a0b-af13-9b9f692fef28)

![image](https://github.com/edustipend/dotorg/assets/41088053/e12e4ea3-014b-47a0-a78f-85257a14a658)

2024-06-07 06:09 UTC, edustipend-root requested changes
Great work on resolving the build failure @Josh-Alhassan, please see my other comments.

2024-06-07 06:09 UTC, edustipend-root commented on src/sections/SupportALearner/BeneficiaryTestimonies/TestimonialCard.jsx
> +import './TestimonialCard.css';
@Josh-Alhassan, this is not how the team convention for importing CSS files. The problem with this approach is that the styling is global instead of being local to the specific component.

What we have adopted is modular CSS where the stylesheet becomes only for that specific component. See https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/

We need to refactor this @Josh-Alhassan, so let me know if you want to do this in a brand new PR so we can merge this one in or in a separate PR.

@RB-Isiaq, please assist @Josh-Alhassan on these changes.

2024-06-07 06:09 UTC, edustipend-root commented on src/sections/SupportALearner/BeneficiaryTestimonies/TestimonialCard.jsx
Please move this `TestimonialCard` into our [src/components](https://github.com/edustipend/dotorg/tree/develop/src/components) folder.

I won't hold up the PR for this but I'd like to see tests at the component level for this and a story file.

2024-06-07 09:25 UTC, Josh-Alhassan commented on src/sections/SupportALearner/BeneficiaryTestimonies/TestimonialCard.jsx
> +import './TestimonialCard.css';
@edustipend-root Thank you for the feedback and the docs. 

Please merge this one. I will create a new PR for the modular CSS.

2024-06-07 09:27 UTC, Josh-Alhassan commented on src/sections/SupportALearner/BeneficiaryTestimonies/TestimonialCard.jsx
@edustipend-root acknowledged. I will do them

2024-06-08 09:24 UTC, edustipend-root commented on package-lock.json
@Josh-Alhassan, please delete this `pacakge-lock.json` file from this PR. We are using `yarn` for managing our dependencies and only need `yarn.lock`

I'll merge this PR once you do.

2024-06-08 09:29 UTC, Josh-Alhassan commented on package-lock.json
@edustipend-root I have removed the `package-lock.json` file.

2024-06-08 09:32 UTC, edustipend-root approved these changes

2024-06-08 09:33 UTC, merged