feat/impact-overview
edustipend/dotorg pull request #169
Opened 2024-06-06 20:56 UTC by misspelz

![image](https://github.com/edustipend/dotorg/assets/99533069/8d84ff4c-a4ca-422e-9860-67af2068f9e6)

2024-06-07 06:01 UTC, edustipend-root requested changes
@misspelz this looks good, but just some minor comments.
Also I didn't see a `.stories`for the `ImpactNumber` component.

2024-06-07 06:01 UTC, edustipend-root commented on src/sections/Impacts/internals/Overview.jsx
> +          <Button label={'View Impact Report'} size={'medium'} type={'secondary'} />
Please add all page copy/strings like `'View Impact Report'` to the `constants.js` file

2024-06-10 12:24 UTC, misspelz commented on src/sections/Impacts/internals/Overview.jsx
> +        <ImpactNumber amount="₦238,700" label="TOTAL DISBURSED" />
Okay

2024-06-10 12:24 UTC, misspelz commented on src/sections/Impacts/internals/Overview.jsx
> +          <Button label={'View Impact Report'} size={'medium'} type={'secondary'} />
Okay

2024-06-10 12:25 UTC, misspelz commented
> @misspelz this looks good, but just some minor comments. Also I didn't see a `.stories`for the `ImpactNumber` component.

Done now

2024-06-10 16:27 UTC, edustipend-root approved these changes

2024-06-10 16:27 UTC, merged