feat/partner-with-us
edustipend/dotorg pull request #170
Opened 2024-06-07 10:31 UTC by misspelz

![image](https://github.com/edustipend/dotorg/assets/99533069/555a9cec-861f-4ec2-be3a-032669281657)

2024-06-08 09:46 UTC, edustipend-root requested changes
Changes look good @misspelz  but some minor comments - let's tweak this and clean it up

2024-06-08 09:46 UTC, edustipend-root commented on src/assets/partnerwithus.png
@misspelz this image is quick large, almost 1MB - that's a lot to be adding to the size of this app. 

Can we get in touch with the designer Ubon and see if we can have a compressed image that isn't this heavy?

2024-06-08 09:46 UTC, edustipend-root commented on src/sections/Impacts/internals/PartnerWithUs.jsx
> +              <Button label={'Support a Learner'} size={'large'} type={'secondary'} />
Please put the `'Support a learner' text into a `constant.js` file.

2024-06-10 11:31 UTC, misspelz commented on src/assets/partnerwithus.png
I just compressed to less than 400mb. How's that?

2024-06-10 11:34 UTC, misspelz commented on src/sections/Impacts/internals/PartnerWithUs.jsx
> +              <Button label={'Support a Learner'} size={'large'} type={'secondary'} />
Done

2024-06-10 21:38 UTC, edustipend-root approved these changes

2024-06-10 21:41 UTC, merged