feat: transparency api consumed for dashboard page and latest donatio…
edustipend/dotorg pull request #174
Opened 2024-06-13 18:04 UTC by RB-Isiaq

> Transparency dashboard api integrated.

![Screenshot 2024-06-13 185129](https://github.com/edustipend/dotorg/assets/99425435/27294ca1-8c15-41fa-8045-a6686209a1e1)
![Screenshot 2024-06-13 185041](https://github.com/edustipend/dotorg/assets/99425435/3a8621c9-57c2-4b8d-8196-fb0d46cf2510)
![Screenshot 2024-06-13 185013](https://github.com/edustipend/dotorg/assets/99425435/07c2c023-d1a7-45de-957b-8b087ff9c849)
![Screenshot 2024-06-13 184951](https://github.com/edustipend/dotorg/assets/99425435/77600014-bbbe-499b-ba70-f8a74b004a23)
![Screenshot 2024-06-13 184929](https://github.com/edustipend/dotorg/assets/99425435/f8fdc4d2-a60c-4c77-9ba0-55e22cc08d0e)
![Screenshot (70)](https://github.com/edustipend/dotorg/assets/99425435/7b1789cf-9719-48ba-9aa2-179b5c9d5b9a)

https://github.com/edustipend/dotorg/assets/99425435/88833777-a993-40a9-911e-53d98fcbd5b8

2024-06-15 15:50 UTC, edustipend-root commented on src/sections/TransparencyDashboard/constants.js
> +  goal: 10000000,
@RB-Isiaq, the goal is 11,000,000.

2024-06-15 15:59 UTC, edustipend-root commented
@RB-Isiaq, I'm seeing an error when I visit https://edustipenddotorg--pr174-feat-transparency-ap-tectirtx.web.app/support-a-learner . Can you please take a look?

2024-06-15 16:07 UTC, edustipend-root commented on src/sections/SupportALearner/LatestDonations/LatestDonations.jsx
> +        <Pagination currentPage={currentPage} onPageChange={changePage} showViewAll={true} totalPages={total} handleNextCall={() => {}} />
`handleNextCall` should route to the Donations dashboard page.

2024-06-15 22:48 UTC, RB-Isiaq commented
> @RB-Isiaq, I'm seeing an error when I visit https://edustipenddotorg--pr174-feat-transparency-ap-tectirtx.web.app/support-a-learner . Can you please take a look?

It has been fixed sir @edustipend-root

2024-06-16 08:49 UTC, edustipend-root commented
> > @RB-Isiaq, I'm seeing an error when I visit https://edustipenddotorg--pr174-feat-transparency-ap-tectirtx.web.app/support-a-learner . Can you please take a look?
> 
> It has been fixed sir @edustipend-root

@RB-Isiaq, here's the screenshot of what I'm seeing when I go to https://edustipenddotorg--pr174-feat-transparency-ap-tectirtx.web.app/transparency-dashboard

![image](https://github.com/edustipend/dotorg/assets/138419840/ed85a2ac-8fff-495c-9fe3-e0e7e66d42fa)

So couple of things here:

- Why are we seeing NaN values?
- If you look at the screenshot closely, you'd see that this build is calling PROD api instead of DEV? Can you please check why that is happening? This should NOT be calling PROD api directly, it should be calling the DEV instance of the service.

Please investigate this urgently. I'm really hoping we have not been making any calls to our PROD api.

2024-06-16 08:49 UTC, edustipend-root requested changes
See my comment

2024-06-16 09:24 UTC, edustipend-root commented
Also @RB-Isiaq, can we change the route for the dashboard to `/support-a-learner/transparency-dashboard` ?

2024-06-16 17:09 UTC, RB-Isiaq commented
> > > @RB-Isiaq, I'm seeing an error when I visit https://edustipenddotorg--pr174-feat-transparency-ap-tectirtx.web.app/support-a-learner . Can you please take a look?
> > 
> > 
> > It has been fixed sir @edustipend-root
> 
> @RB-Isiaq, here's the screenshot of what I'm seeing when I go to https://edustipenddotorg--pr174-feat-transparency-ap-tectirtx.web.app/transparency-dashboard
> 
> ![image](https://private-user-images.githubusercontent.com/138419840/340078046-ed85a2ac-8fff-495c-9fe3-e0e7e66d42fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NTc1NTMsIm5iZiI6MTcxODU1NzI1MywicGF0aCI6Ii8xMzg0MTk4NDAvMzQwMDc4MDQ2LWVkODVhMmFjLThmZmYtNDk1Yy05ZmUzLWUwZTdlNjZkNDJmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQxNzAwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZGEwYWViZDMyNjQ4YjQ2YTQ2YzZiMzgzMzNiMWI2MTI4MDJmZjNjZWIzNjc1NTlmNzM5MmZiMmI4OWIxMzlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PEPXmSfSuKfHIKIdMgZDWzU0F5jN8uDaOyTxBiZ5SFA)
> 
> So couple of things here:
> 
> * Why are we seeing NaN values?
> * If you look at the screenshot closely, you'd see that this build is calling PROD api instead of DEV? Can you please check why that is happening? This should NOT be calling PROD api directly, it should be calling the DEV instance of the service.
> 
> Please investigate this urgently. I'm really hoping we have not been making any calls to our PROD api.

So @edustipend-root  about this, the pr links actually call the prod api all the time, probably because it sees it as a production site.
This is a screenshot from @Ezeh20 pr.
![Screenshot (76)](https://github.com/edustipend/dotorg/assets/99425435/786da502-a25e-445f-a10d-2ea7abe89a45)
![Screenshot (75)](https://github.com/edustipend/dotorg/assets/99425435/f5ffaed8-5dd9-40bc-87a5-a713ad48a595)

![image](https://github.com/edustipend/dotorg/assets/99425435/3a490a41-0d9d-4fb5-8155-e3d40ce39aed)
![Screenshot (77)](https://github.com/edustipend/dotorg/assets/99425435/86334f9d-511a-42c8-b615-263d607befa7)

But then, when you run it up on localhost, it sees it as the dev environment, and uses the dev api.
See this sir:
![image](https://github.com/edustipend/dotorg/assets/99425435/f78531d0-e017-47af-bfdf-d4207054e97d)
![image](https://github.com/edustipend/dotorg/assets/99425435/96360d9b-abab-4307-8921-f459c2403557)

2024-06-16 17:26 UTC, edustipend-root commented
> > > > @RB-Isiaq, I'm seeing an error when I visit https://edustipenddotorg--pr174-feat-transparency-ap-tectirtx.web.app/support-a-learner . Can you please take a look?
> > > 
> > > 
> > > It has been fixed sir @edustipend-root
> > 
> > 
> > @RB-Isiaq, here's the screenshot of what I'm seeing when I go to https://edustipenddotorg--pr174-feat-transparency-ap-tectirtx.web.app/transparency-dashboard
> > ![image](https://private-user-images.githubusercontent.com/138419840/340078046-ed85a2ac-8fff-495c-9fe3-e0e7e66d42fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NTc1NTMsIm5iZiI6MTcxODU1NzI1MywicGF0aCI6Ii8xMzg0MTk4NDAvMzQwMDc4MDQ2LWVkODVhMmFjLThmZmYtNDk1Yy05ZmUzLWUwZTdlNjZkNDJmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQxNzAwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZGEwYWViZDMyNjQ4YjQ2YTQ2YzZiMzgzMzNiMWI2MTI4MDJmZjNjZWIzNjc1NTlmNzM5MmZiMmI4OWIxMzlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PEPXmSfSuKfHIKIdMgZDWzU0F5jN8uDaOyTxBiZ5SFA)
> > So couple of things here:
> > 
> > * Why are we seeing NaN values?
> > * If you look at the screenshot closely, you'd see that this build is calling PROD api instead of DEV? Can you please check why that is happening? This should NOT be calling PROD api directly, it should be calling the DEV instance of the service.
> > 
> > Please investigate this urgently. I'm really hoping we have not been making any calls to our PROD api.
> 
> So @edustipend-root about this, the pr links actually call the prod api all the time, probably because it sees it as a production site. This is a screenshot from @Ezeh20 pr. ![Screenshot (76)](https://private-user-images.githubusercontent.com/99425435/340119854-786da502-a25e-445f-a10d-2ea7abe89a45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NTkwMjIsIm5iZiI6MTcxODU1ODcyMiwicGF0aCI6Ii85OTQyNTQzNS8zNDAxMTk4NTQtNzg2ZGE1MDItYTI1ZS00NDVmLWExMGQtMmVhN2FiZTg5YTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDE3MjUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxOWI0NjJkNmFiZWRkYWI4MmFiYmUzNzU1MDM1Y2E1YmJkNmJkNzg2MTdmYzA3NGIzNDZiZTQ2NDhhMDQ1NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fBjTfkOtVS45869hpKEtnSq-QilRInql6D12Fzewnj0) ![Screenshot (75)](https://private-user-images.githubusercontent.com/99425435/340119858-f5ffaed8-5dd9-40bc-87a5-a713ad48a595.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NTkwMjIsIm5iZiI6MTcxODU1ODcyMiwicGF0aCI6Ii85OTQyNTQzNS8zNDAxMTk4NTgtZjVmZmFlZDgtNWRkOS00MGJjLTg3YTUtYTcxM2FkNDhhNTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDE3MjUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMGY2MmFlYTUxODIzYzE2YTM0NTFmYTFjMmU1NDZjNDlhYmZhYzk2MGU0YzRmZjAwNjIwZDU3MmM2ZWIwMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DeLHFl7YqbqW-PLtAcgL8SG3pzwZ8GA-wDm-ba7Z1tA)
> 
> ![image](https://private-user-images.githubusercontent.com/99425435/340119831-3a490a41-0d9d-4fb5-8155-e3d40ce39aed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NTkwMjIsIm5iZiI6MTcxODU1ODcyMiwicGF0aCI6Ii85OTQyNTQzNS8zNDAxMTk4MzEtM2E0OTBhNDEtMGQ5ZC00ZmI1LTgxNTUtZTNkNDBjZTM5YWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDE3MjUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMTliMTk5YTFiYmExNDg5NjE1ZjkwMTU3MGNmN2VlOTQzZjAxYWFjNGY4NDAwMTI5MjY2ZGRhNzY5M2QxZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y5X8PwqzsR7QLNAYBK7g5hfmXyH_HQ-NlGkunELP3Ak) ![Screenshot (77)](https://private-user-images.githubusercontent.com/99425435/340119847-86334f9d-511a-42c8-b615-263d607befa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NTkwMjIsIm5iZiI6MTcxODU1ODcyMiwicGF0aCI6Ii85OTQyNTQzNS8zNDAxMTk4NDctODYzMzRmOWQtNTExYS00MmM4LWI2MTUtMjYzZDYwN2JlZmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDE3MjUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMTQwZDJjMDBjODk3ZjYwYTBmNGI2YzU0YTk3NzhlMzRjZDMwMWJlODYyZjFlNDUyMmZmYWQ3N2EzZTM2YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OwOYvfhuleiWOE4SDFer1moHdpZ8oETeZexVLZHYtkc)
> 
> But then, when you run it up on localhost, it sees it as the dev environment, and uses the dev api. See this sir: ![image](https://private-user-images.githubusercontent.com/99425435/340120052-f78531d0-e017-47af-bfdf-d4207054e97d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NTkwMjIsIm5iZiI6MTcxODU1ODcyMiwicGF0aCI6Ii85OTQyNTQzNS8zNDAxMjAwNTItZjc4NTMxZDAtZTAxNy00N2FmLWJmZGYtZDQyMDcwNTRlOTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDE3MjUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5MWJiNzE1YWQ4NWQzMTk3MzY1YjNkYjIyOGUxZTMwZDU2Yjg2ZmY5N2RiOWYwYzUwMmFjMjViYzIwMDEyNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MtGdYiFyuoTMtqbVE6bxNzyisEp7XNnsz1i4JvM8eK0) ![image](https://private-user-images.githubusercontent.com/99425435/340120072-96360d9b-abab-4307-8921-f459c2403557.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NTkwMjIsIm5iZiI6MTcxODU1ODcyMiwicGF0aCI6Ii85OTQyNTQzNS8zNDAxMjAwNzItOTYzNjBkOWItYWJhYi00MzA3LTg5MjEtZjQ1OWMyNDAzNTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDE3MjUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkM2JlYzY2OTk5M2EwOTQ3OTZmNWNmYzliYThjMWFlOWFkNjUxOTQwZTA2M2ZmNDAyZjJjOGJlMjFlODRmN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LvS2RcuTCWGdPNQWxzxH6XxLv127quD6hvbu1OGIe78)

Thanks @RB-Isiaq for investigating this, this is gonna be a problem because when we want the team to test tomorrow, we want them testing against DEV api not PROD api. I have to figure out a way for the build to point to DEV not PROD.

I'll approve and get this merged in for now.

2024-06-16 17:28 UTC, edustipend-root approved these changes

2024-06-16 17:28 UTC, merged

2024-06-16 17:32 UTC, RB-Isiaq commented
> > > > > @RB-Isiaq, I'm seeing an error when I visit https://edustipenddotorg--pr174-feat-transparency-ap-tectirtx.web.app/support-a-learner . Can you please take a look?
> > > > 
> > > > 
> > > > It has been fixed sir @edustipend-root
> > > 
> > > 
> > > @RB-Isiaq, here's the screenshot of what I'm seeing when I go to https://edustipenddotorg--pr174-feat-transparency-ap-tectirtx.web.app/transparency-dashboard
> > > ![image](https://private-user-images.githubusercontent.com/138419840/340078046-ed85a2ac-8fff-495c-9fe3-e0e7e66d42fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NTc1NTMsIm5iZiI6MTcxODU1NzI1MywicGF0aCI6Ii8xMzg0MTk4NDAvMzQwMDc4MDQ2LWVkODVhMmFjLThmZmYtNDk1Yy05ZmUzLWUwZTdlNjZkNDJmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQxNzAwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZGEwYWViZDMyNjQ4YjQ2YTQ2YzZiMzgzMzNiMWI2MTI4MDJmZjNjZWIzNjc1NTlmNzM5MmZiMmI4OWIxMzlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PEPXmSfSuKfHIKIdMgZDWzU0F5jN8uDaOyTxBiZ5SFA)
> > > So couple of things here:
> > > 
> > > * Why are we seeing NaN values?
> > > * If you look at the screenshot closely, you'd see that this build is calling PROD api instead of DEV? Can you please check why that is happening? This should NOT be calling PROD api directly, it should be calling the DEV instance of the service.
> > > 
> > > Please investigate this urgently. I'm really hoping we have not been making any calls to our PROD api.
> > 
> > 
> > So @edustipend-root about this, the pr links actually call the prod api all the time, probably because it sees it as a production site. This is a screenshot from @Ezeh20 pr. ![Screenshot (76)](https://private-user-images.githubusercontent.com/99425435/340119854-786da502-a25e-445f-a10d-2ea7abe89a45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NTkwMjIsIm5iZiI6MTcxODU1ODcyMiwicGF0aCI6Ii85OTQyNTQzNS8zNDAxMTk4NTQtNzg2ZGE1MDItYTI1ZS00NDVmLWExMGQtMmVhN2FiZTg5YTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDE3MjUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxOWI0NjJkNmFiZWRkYWI4MmFiYmUzNzU1MDM1Y2E1YmJkNmJkNzg2MTdmYzA3NGIzNDZiZTQ2NDhhMDQ1NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fBjTfkOtVS45869hpKEtnSq-QilRInql6D12Fzewnj0) ![Screenshot (75)](https://private-user-images.githubusercontent.com/99425435/340119858-f5ffaed8-5dd9-40bc-87a5-a713ad48a595.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NTkwMjIsIm5iZiI6MTcxODU1ODcyMiwicGF0aCI6Ii85OTQyNTQzNS8zNDAxMTk4NTgtZjVmZmFlZDgtNWRkOS00MGJjLTg3YTUtYTcxM2FkNDhhNTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDE3MjUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMGY2MmFlYTUxODIzYzE2YTM0NTFmYTFjMmU1NDZjNDlhYmZhYzk2MGU0YzRmZjAwNjIwZDU3MmM2ZWIwMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DeLHFl7YqbqW-PLtAcgL8SG3pzwZ8GA-wDm-ba7Z1tA)
> > ![image](https://private-user-images.githubusercontent.com/99425435/340119831-3a490a41-0d9d-4fb5-8155-e3d40ce39aed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NTkwMjIsIm5iZiI6MTcxODU1ODcyMiwicGF0aCI6Ii85OTQyNTQzNS8zNDAxMTk4MzEtM2E0OTBhNDEtMGQ5ZC00ZmI1LTgxNTUtZTNkNDBjZTM5YWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDE3MjUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMTliMTk5YTFiYmExNDg5NjE1ZjkwMTU3MGNmN2VlOTQzZjAxYWFjNGY4NDAwMTI5MjY2ZGRhNzY5M2QxZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y5X8PwqzsR7QLNAYBK7g5hfmXyH_HQ-NlGkunELP3Ak) ![Screenshot (77)](https://private-user-images.githubusercontent.com/99425435/340119847-86334f9d-511a-42c8-b615-263d607befa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NTkwMjIsIm5iZiI6MTcxODU1ODcyMiwicGF0aCI6Ii85OTQyNTQzNS8zNDAxMTk4NDctODYzMzRmOWQtNTExYS00MmM4LWI2MTUtMjYzZDYwN2JlZmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDE3MjUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMTQwZDJjMDBjODk3ZjYwYTBmNGI2YzU0YTk3NzhlMzRjZDMwMWJlODYyZjFlNDUyMmZmYWQ3N2EzZTM2YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OwOYvfhuleiWOE4SDFer1moHdpZ8oETeZexVLZHYtkc)
> > But then, when you run it up on localhost, it sees it as the dev environment, and uses the dev api. See this sir: ![image](https://private-user-images.githubusercontent.com/99425435/340120052-f78531d0-e017-47af-bfdf-d4207054e97d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NTkwMjIsIm5iZiI6MTcxODU1ODcyMiwicGF0aCI6Ii85OTQyNTQzNS8zNDAxMjAwNTItZjc4NTMxZDAtZTAxNy00N2FmLWJmZGYtZDQyMDcwNTRlOTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDE3MjUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5MWJiNzE1YWQ4NWQzMTk3MzY1YjNkYjIyOGUxZTMwZDU2Yjg2ZmY5N2RiOWYwYzUwMmFjMjViYzIwMDEyNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MtGdYiFyuoTMtqbVE6bxNzyisEp7XNnsz1i4JvM8eK0) ![image](https://private-user-images.githubusercontent.com/99425435/340120072-96360d9b-abab-4307-8921-f459c2403557.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NTkwMjIsIm5iZiI6MTcxODU1ODcyMiwicGF0aCI6Ii85OTQyNTQzNS8zNDAxMjAwNzItOTYzNjBkOWItYWJhYi00MzA3LTg5MjEtZjQ1OWMyNDAzNTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDE3MjUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkM2JlYzY2OTk5M2EwOTQ3OTZmNWNmYzliYThjMWFlOWFkNjUxOTQwZTA2M2ZmNDAyZjJjOGJlMjFlODRmN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LvS2RcuTCWGdPNQWxzxH6XxLv127quD6hvbu1OGIe78)
> 
> Thanks @RB-Isiaq for investigating this, this is gonna be a problem because when we want the team to test tomorrow, we want them testing against DEV api not PROD api. I have to figure out a way for the build to point to DEV not PROD.
> 
> I'll approve and get this merged in for now.

Alright no problem, Thank you. @edustipend-root