integrated the report links
edustipend/dotorg pull request #175
Opened 2024-06-16 00:09 UTC by RB-Isiaq

>  Integrated the hosted report links

![Screenshot (74)](https://github.com/edustipend/dotorg/assets/99425435/5063c611-885a-448b-9ea7-f7640b41f939)
![Screenshot (73)](https://github.com/edustipend/dotorg/assets/99425435/4dfbcf28-465c-49fc-ac3d-cc020ca0a8aa)
![Screenshot (72)](https://github.com/edustipend/dotorg/assets/99425435/39b4ed73-495e-4f4e-b9f8-02dc00ed18b2)
![Screenshot (71)](https://github.com/edustipend/dotorg/assets/99425435/57331be5-3cd4-4cb9-bdaa-ea4c940baeaf)

2024-06-16 09:27 UTC, edustipend-root commented on src/sections/Reports/constants.js
> +  // generateReports('August', 2023, [`${HOST_URL}`, `${HOST_URL}`, `${HOST_URL}`]),
@RB-Isiaq, please remove the comments. We don't have reports for those months.

2024-06-16 09:28 UTC, edustipend-root commented on src/sections/Reports/constants.js
> +    `${HOST_URL}2024%2F02%2FEdustipend%20Beneficiaries%20List%20-%20February%202024.pdf?alt=media&token=7f26bd0a-2ed3-49fa-a6a6-1ab89027e85b`,
@RB-Isiaq, you can remove the `token` param from the links. We don't need to expose that - this applies to all the links.

2024-06-16 09:28 UTC, edustipend-root requested changes
Great job @RB-Isiaq, and thanks for the quick turnaround. Just some minor comments and we should be good to merge this in.

2024-06-16 17:33 UTC, RB-Isiaq commented
> Great job @RB-Isiaq, and thanks for the quick turnaround. Just some minor comments and we should be good to merge this in.

@edustipend-root comments have been resolved, you can merge it in now. Thanks.

2024-06-17 09:16 UTC, edustipend-root approved these changes

2024-06-17 09:16 UTC, merged