Feat/refer page
edustipend/dotorg pull request #195
Opened 2024-07-19 08:56 UTC by Josh-Alhassan

![edustipend-refer-page](https://github.com/user-attachments/assets/2875ed55-1082-4b7b-aee8-d36df369e81e)

2024-07-20 07:04 UTC, edustipend-root requested changes
Hello @Josh-Alhassan, thanks for working on this and raising a PR quickly. The changes look good for the most part but I've added some comments on some minor changes.

Also, I didn't see you implement the copy functionality. Was that to be in a separate follow-up PR?

Finally, there are some dissimilarities between your UI and the Figma design. Please take a look at the screenshots below (pay attention to the input fields):

**Your UI**
![image](https://github.com/user-attachments/assets/10fd8ac0-9043-4290-8010-d892cfb02bb2)

**Figma Design**
![image](https://github.com/user-attachments/assets/c2ac85e9-df4d-4957-854e-02e27889fbfc)

Please make the changes and let me know once you've pushed them so I can review and merge this in.

2024-07-20 13:44 UTC, Josh-Alhassan commented on src/pages/refer-page/ReferPageText.js
![image](https://github.com/user-attachments/assets/e9b4fd8f-0612-445a-b861-cb93a19506e5)

I just checked mine and it's the same as the Figam Design. I think it's a rendering issue, maybe at your end. But I will look into it with other devices to make sure it's all consistent.

2024-07-20 14:11 UTC, Josh-Alhassan commented on src/pages/refer-page/ReferPageText.js
> +const referPageTexts = {
referPageTexts, renamed to referralPageCopy

2024-07-20 14:12 UTC, Josh-Alhassan commented on src/pages/refer-page/ReferPageText.js
`ReferPageText.js` is changed to `constants.js`

2024-07-20 14:17 UTC, Josh-Alhassan commented on src/routesConstant.js
> +  REFERRAL_PAGE: '/referral-page'
Route path update to `/support-a-learner/refer-a-friend`

2024-07-20 14:28 UTC, Josh-Alhassan commented on src/pages/refer-page/ReferPage.test.js
> +    expect(screen.getByText('Generate Link')).toBeInTheDocument();
Refactored. "Generate Link" text no longer hardcoded

2024-07-20 14:50 UTC, Josh-Alhassan commented on src/components/FormInput/FormInput.jsx
> +      <input className={styles.inputField} type={type} placeholder={placeholder} />
I have deleted the input component I created and imported the already created `<Input />`  component. It's fixed now.

2024-07-20 15:07 UTC, Josh-Alhassan commented on src/pages/refer-page/ReferPageText.js
@edustipend-root The "copy" functionality is done. I think all corrections have been fixed.

2024-07-21 23:46 UTC, edustipend-root approved these changes
The work to make the API call to get the link will be in a follow-up PR once the BE is implemented.

2024-07-21 23:46 UTC, edustipend-root commented on src/pages/refer-page/ReferPage.jsx
> +            <Input value="Enter name" label="Name" placeholder="Enter name" className={styles.entry} />
@Josh-Alhassan, this is not correct - you are setting the value of the input field to `"Enter name"`. How is this meant to update when the user types in a new value? 

Same applies for the email field below.

2024-07-21 23:46 UTC, edustipend-root commented on src/pages/refer-page/ReferPage.jsx
> +            <Input value="Enter name" label="Name" placeholder="Enter name" className={styles.entry} />
Did you actually test this out that it works?

2024-07-21 23:46 UTC, edustipend-root commented on src/pages/refer-page/ReferPage.jsx
> +            <Input value="Enter name" label="Name" placeholder="Enter name" className={styles.entry} />
@Josh-Alhassan, I pushed a commit to fix it - so we should be good now.

2024-07-21 23:47 UTC, merged