update team images
edustipend/dotorg pull request #203
Opened 2024-08-02 18:10 UTC by Josh-Alhassan

![image](https://github.com/user-attachments/assets/8aa3fe04-6880-47c9-a09e-dc0bff535877)

@edustipend-root here's my changes

2024-08-03 12:42 UTC, edustipend-root requested changes
@Josh-Alhassan, please see my comments

2024-08-03 12:42 UTC, edustipend-root commented on src/sections/MeetTheTeam/MeetTheTeam.jsx
> +  { name: 'Akujobi Chiemezuo', role: 'Backend Developer', img: linkToAkujobiImage },
@Josh-Alhassan, why are we using `Backend Developer` instead of `Backend Engineer` since we used `Frontend Engineer` for the front-end

I'd like for us to stay consistent with what we use.

2024-08-03 12:42 UTC, edustipend-root commented on src/sections/MeetTheTeam/MeetTheTeam.jsx
> +  { name: 'Nester Nwadike', role: 'UX Researcher', img: linkToNesterImage },
Please update this to `UI/UX Researcher` and do the same for Enobong Akpan as well

2024-08-03 12:42 UTC, edustipend-root commented on src/sections/MeetTheTeam/MeetTheTeam.jsx
> +  { name: 'Ubon Udonkang', role: 'UIUX Designer', img: linkToUbonImage },
Please update Ubon's role to `UI/UX Designer` not `UIUX Designer`

2024-08-03 12:42 UTC, edustipend-root commented on src/sections/MeetTheTeam/MeetTheTeam.jsx
>  var settings = {
Is there a reason why we are using `var` here instead of `const`?

2024-08-03 21:47 UTC, Josh-Alhassan commented on src/sections/MeetTheTeam/MeetTheTeam.jsx
> +  { name: 'Akujobi Chiemezuo', role: 'Backend Developer', img: linkToAkujobiImage },
@edustipend-root I have changed it to `Backend Engineer`

2024-08-03 21:48 UTC, Josh-Alhassan commented on src/sections/MeetTheTeam/MeetTheTeam.jsx
> +  { name: 'Nester Nwadike', role: 'UX Researcher', img: linkToNesterImage },
@edustipend-root I have made changes to the correction

2024-08-03 21:48 UTC, Josh-Alhassan commented on src/sections/MeetTheTeam/MeetTheTeam.jsx
> +  { name: 'Ubon Udonkang', role: 'UIUX Designer', img: linkToUbonImage },
@edustipend-root Same as this. I have made changes to the correction

2024-08-03 21:49 UTC, Josh-Alhassan commented on src/sections/MeetTheTeam/MeetTheTeam.jsx
>  var settings = {
Nothing in particular. I have changed it to `const`

2024-08-05 04:06 UTC, edustipend-root approved these changes

2024-08-05 04:06 UTC, merged