Component/input
edustipend/dotorg pull request #31
Opened 2023-07-20 10:53 UTC by Ezeh20

- The Inpunt component is ready for review

**Props**
- label
- placeholder
- dispatch
- dispatchType
- value
- size {optional}
- type (text, email, password, number)

![Screenshot (34)](https://github.com/edustipend/dotorg/assets/29344226/5599a44d-cc49-4f4d-9065-4c739eedab88)

2023-07-20 11:25 UTC, edustipend-root commented
Hello @Ezeh20, your branch name should start with `feature` or `chore`. I would expect this to be something like `feature/input-component`

2023-07-20 15:24 UTC, edustipend-root requested changes

2023-07-20 15:24 UTC, edustipend-root commented on src/components/Input/Input.jsx
> +        {lable} <span className={styles.required}>*</span>
@Ezeh20, there's a typo here. Should this be `label` not `lable`?

2023-07-20 15:24 UTC, edustipend-root commented on src/components/Input/Input.jsx
> +  lable: PropTypes.string,
Please check typo, this should be `label` not `lable`

2023-07-20 15:24 UTC, edustipend-root commented on yarn.lock
Run `yarn install` to overwrite these file. There are some conflict markers in this file @Ezeh20

2023-07-21 19:06 UTC, Ezeh20 commented on src/components/Input/Input.jsx
> +        {lable} <span className={styles.required}>*</span>
yeah, it's a typo 
i will correct it

2023-07-21 19:06 UTC, Ezeh20 commented on src/components/Input/Input.jsx
> +  lable: PropTypes.string,
on it

2023-07-21 19:16 UTC, Ezeh20 commented on src/components/Input/Input.jsx
> +  dispatch: PropTypes.func,
I thought of a way to handle the entire process. Basically we will use a reducer to store all the states till will get to the final step
const [state, dispatch] = useReducer(requestReducer, INITIAL_STATE)
const {fullName, email, etc}= state
these states can then be submitted to the backend after everything.
body = {
fullName,
email,
etc
}

We can update the INITIAL_STATE states in the requestReducer  when we pass the dispatch to the components.

2023-07-22 11:57 UTC, edustipend-root commented on src/components/Input/Input.jsx
> +  dispatch: PropTypes.func,
Hey @Ezeh20, using a reducer for an input component like this makes the component too logic-heavy. Ideally, we want our components to be as light as possible with minimal logic.

Since this is just an input component and we want to track the value of the input field, we can manage this just by using state right?

Also, I'll expect that this component should have a `type` prop that should have values `'email' | 'password', 'number' | 'text'`

2023-07-22 12:41 UTC, Ezeh20 commented on src/components/Input/Input.jsx
> +  dispatch: PropTypes.func,
Good afternoon sir, yes we can use a useState but it may not be manageable 
considering the size of the Form. I can remove it if there is a better way to handle the states.

Yes there is a type prop

2023-07-24 08:39 UTC, merged