Feature/button customization
edustipend/dotorg pull request #33
Opened 2023-07-20 21:56 UTC by Ezeh20

- added a disabled state to the button and gave additional styles to button because the buttons are not consistent all through.

**New Props**
- disabled (false by default)
- back (<)
- forward (>)
- plain (use for plain buttons)
- request (use this prop for the request work flow as the design is a little bit different) 
![Uploading Screenshot (36).png…]()

2023-07-24 08:55 UTC, edustipend-root requested changes
Good job @Ezeh20, added some comments on where I think we can improve.

2023-07-24 08:55 UTC, edustipend-root commented on src/components/Button/Button.jsx
> +        {back && (
This is a good attempt at this @Ezeh20.

But I think a better way to write this would be to abstract the logic for the icon so that this button can accept any icon going forward.

So the prop should be something like `icon` which will be an image and `iconPosition` which will have two values `'back' | 'front'` to determine whether to place the icon in front of the button label.

That way whoever the `Button` is easily extensible and whoever is using the `Button` component can pass in whatever icon they want instead of hard-coding it to be these two arrows.

Lmk if that makes sense.

Tagging you @misspelz  and @RB-Isiaq as well because I think you might learn something from this.

2023-07-24 08:55 UTC, edustipend-root commented on src/components/Button/styles.css
> +.request-section {
@Ezeh20, I don't think we should be adding this here. 
The styling here should be very specific to the `Button` component.
Instead whatever styles we want to apply to the button should be passed via the `className` prop.

2023-07-24 08:55 UTC, edustipend-root commented on src/components/Button/styles.css
> +.arrow {
Let's rename this to `icon` to make it more generic for any icon that is passed as a prop to this `Button` component.

2023-07-24 08:55 UTC, edustipend-root commented on src/components/Button/styles.css
> +  .request-section {
Please remove any page-level styling from the button styles.

2023-07-24 08:55 UTC, edustipend-root commented on src/components/Button/styles.css
> +  .arrow_left {
We can rename this to `back-icon` to match with the prop name.

2023-07-24 08:55 UTC, edustipend-root commented on src/components/Button/styles.css
> +  .arrow_right {
We can rename this to `front-icon` to match with the prop name.

2023-07-25 12:55 UTC, Ezeh20 commented on src/components/Button/Button.jsx
> +        {back && (
Alright sir

2023-07-25 14:06 UTC, Ezeh20 commented on src/components/Button/styles.css
> +.request-section {
added the className prop

2023-07-25 14:06 UTC, Ezeh20 commented on src/components/Button/styles.css
> +  .arrow_left {
done

2023-07-25 14:07 UTC, Ezeh20 commented on src/components/Button/styles.css
> +  .request-section {
done

2023-07-26 12:48 UTC, edustipend-root approved these changes

2023-07-26 12:50 UTC, misspelz approved these changes

2023-07-26 12:50 UTC, merged