Feature/edustipend at one
edustipend/dotorg pull request #43
Opened 2023-08-03 09:02 UTC by RB-Isiaq

This Pr contains the components for the edustipend at one page.

1. The Achievement component
2. The Timelines component
3. The AtOne page

2023-08-04 07:20 UTC, RB-Isiaq commented
![Screenshot_20230804-081805](https://github.com/edustipend/dotorg/assets/99425435/276f3af3-2510-4bf5-804f-b5a8392b4bb8)

I deleted the plain: false in the Button.defaultProps, because it was throwing an error in the console, as plain is no longer a boolean property.

2023-08-05 14:59 UTC, edustipend-root requested changes
Looks good, just some minor comments.

2023-08-05 14:59 UTC, edustipend-root commented on src/assets/Downloads/(0xc000007b).zip
Hello @RB-Isiaq, can we delete this downloads folder?

2023-08-05 14:59 UTC, edustipend-root commented on src/sections/Timelines/__tests__/Timelines.test.js
@RB-Isiaq, we should add a test for the button click handler to ensure that it renders the right amount of paginated content.

You can do that in a follow-up PR.

2023-08-06 05:44 UTC, RB-Isiaq commented on src/assets/Downloads/(0xc000007b).zip
Done sir

2023-08-06 05:48 UTC, RB-Isiaq commented on src/sections/Timelines/__tests__/Timelines.test.js
Done

2023-08-07 09:09 UTC, edustipend-root approved these changes
LGTM!

2023-08-07 09:10 UTC, merged