Feature/learner dashboard
edustipend/dotorg pull request #44
Opened 2023-08-04 15:10 UTC by Ezeh20

- This PR contains the home section of the learner's dashboard
- Routed the dashboard path
- Created a table component
- Made the layout for other sections of the dashboard
- Made room for the sidebar

**/dashboard navigates to the dashboard** 

**The main navbar has a fixed position which make  contents go behind it, it's either we change it to sticky and a top of 0
or we do a margin-top for every page** 

**The last screenshot is not included in the file**

![Screenshot (44)](https://github.com/edustipend/dotorg/assets/29344226/87024164-d552-475c-aa28-fcbd62315a38)
![Screenshot (45)](https://github.com/edustipend/dotorg/assets/29344226/6f6596b4-b1b7-4905-9bcd-358a31ea492e)
![Screenshot (46)](https://github.com/edustipend/dotorg/assets/29344226/ffa1d92d-3667-4df3-af77-b247f82b5fc8)

2023-08-05 15:05 UTC, edustipend-root requested changes
Looks good @Ezeh20, great job and thanks for adding the screenshots.
Please take note of the comments I made and when you address those, I'll get it merged.

2023-08-05 15:05 UTC, edustipend-root commented on src/components/Table/internals/Table2/Table2.jsx
> +                                            : Application_Status === 'In review' ? 'in_view bold_weight'
Is there a way we can avoid having hard-coded strings?

2023-08-05 15:05 UTC, edustipend-root commented on src/components/Table/internals/Table2/Table2.module.css
> +    color: #2D3740;
Can we add this color to a CSS variable?

2023-08-05 15:05 UTC, edustipend-root commented on src/components/Table/internals/Table2/Table2.module.css
> +    background-color: #ECEDEF;
Add this as a CSS variable in `colors.css`

2023-08-05 21:06 UTC, Ezeh20 commented
@edustipend-root I have made the changes

2023-08-07 10:54 UTC, Ezeh20 commented
> Looks good @Ezeh20, great job and thanks for adding the screenshots. Please take note of the comments I made and when you address those, I'll get it merged.

Done

2023-08-07 19:13 UTC, edustipend-root approved these changes

2023-08-07 19:13 UTC, merged