Feature/sidebar-component
edustipend/dotorg pull request #45
Opened 2023-08-04 15:57 UTC by misspelz

![sidebar](https://github.com/edustipend/dotorg/assets/99533069/b6b6dffc-8801-4a3d-82f9-4f5dec080d19)

2023-08-05 15:02 UTC, edustipend-root requested changes
LGTM! Just some minor changes to be made.
Good work @misspelz!

2023-08-05 15:02 UTC, edustipend-root commented on src/components/Quote/Quote.jsx
> +  // boldcontent: 'Bold Text',
Hello @misspelz, please remove this comment.

2023-08-05 15:02 UTC, edustipend-root commented on src/components/SideBar/contants.js
> +    boldquote: 'Did you know?',
Can we rename this to `title` or `header` instead of `boldquote`?

2023-08-05 18:53 UTC, misspelz commented on src/components/SideBar/contants.js
> +    boldquote: 'Did you know?',
Done

2023-08-05 18:53 UTC, misspelz commented on src/components/Quote/Quote.jsx
> +  // boldcontent: 'Bold Text',
Done

2023-08-07 09:12 UTC, edustipend-root approved these changes
Looks good @misspelz, merging now!

2023-08-07 09:12 UTC, merged