Feature/quote-component
edustipend/dotorg pull request #46
Opened 2023-08-05 18:49 UTC by misspelz

Comments have been removed

2023-08-07 09:21 UTC, edustipend-root requested changes
@misspelz, you opened this PR against `main` instead of `develop`. Please update the base branch to the correct one.

2023-08-19 12:13 UTC, edustipend-root requested changes
Please open your PRs against the right branch @misspelz

2023-08-19 12:22 UTC, misspelz commented
> Please open your PRs against the right branch @misspelz

I am sorry about that. I just changed the base branch back to develop

2023-08-28 06:01 UTC, edustipend-root approved these changes

2023-08-28 06:01 UTC, merged