Feature/no-internet-component
edustipend/dotorg pull request #57
Opened 2023-08-17 21:09 UTC by misspelz

![image](https://github.com/edustipend/dotorg/assets/99533069/ab239896-a5b1-4d97-b9d4-b42cfa4eb30d)

I wrote the logic in the component for review but I have tested it in the App.js where I put the logic and conditionally rendered the component and it worked

Is there a better way to write the logic?

Kindly review

2023-08-19 12:08 UTC, edustipend-root requested changes
Hello @misspelz, you opened this PR against `main` instead of `develop`.
Please ensure that you open your PRs against the right branch.

2023-08-20 15:38 UTC, edustipend-root requested changes
Looks good @misspelz, some minor changes need to be made.

2023-08-20 15:38 UTC, edustipend-root commented on src/components/NoInternet/NoInternet.jsx
This is good @misspelz, but I think this will serve better if written as a custom hook.
Because we want to be able to display this component on every page the user is once their internet goes off.

Have you written one before?

2023-08-20 15:38 UTC, edustipend-root commented on src/components/NoInternet/NoInternet.jsx
> +  console.log(isOnline);
Please remove the `console.log` message

2023-08-20 15:38 UTC, edustipend-root commented on src/components/NoInternet/NoInternet.jsx
> +        <h3 data-testid={NO_INTERNET_CONNECTION_TEXT_TEST_ID} className={styles.header}>No Internet Connection</h3>
Is there a reason we aren't using our `<Header />` component here?

2023-08-20 21:58 UTC, misspelz commented on src/components/NoInternet/NoInternet.jsx
> +  console.log(isOnline);
I have removed it

2023-08-20 22:01 UTC, misspelz commented on src/components/NoInternet/NoInternet.jsx
> +        <h3 data-testid={NO_INTERNET_CONNECTION_TEXT_TEST_ID} className={styles.header}>No Internet Connection</h3>
I have used both the header and text

2023-08-20 22:09 UTC, misspelz commented on src/components/NoInternet/NoInternet.jsx
No, I have not

2023-08-23 09:58 UTC, edustipend-root requested changes
Looks a lot better.
Just some minor changes to be made.

2023-08-23 09:58 UTC, edustipend-root commented on src/components/NoInternet/CustomNoInternet.jsx
This is better @misspelz, great job.
But this shouldn't be a component, it should be a hook.
So let's rename this to `useDetectInternet` and move it to `src/hooks/useDetectInternet`

2023-08-23 11:11 UTC, misspelz commented on src/components/NoInternet/CustomNoInternet.jsx
Okay, sir. I am on it

2023-08-28 06:00 UTC, merged