Feature/loading spinner
edustipend/dotorg pull request #59
Opened 2023-08-19 18:54 UTC by Ezeh20

- This PR holds the loading spinner and the loading message 

![Screenshot (80)](https://github.com/edustipend/dotorg/assets/29344226/6a970e20-18cb-4692-b34a-47be2e1a4810)
![Screenshot (79)](https://github.com/edustipend/dotorg/assets/29344226/5b9e1c48-070a-4143-9124-5f3bb56076bb)

2023-08-20 15:34 UTC, edustipend-root requested changes
Good job @Ezeh20, some minor changes I would like that you address.

2023-08-20 15:34 UTC, edustipend-root commented on src/components/LoadingMessage/internals/constants.js
> +export const randomMessage = (array, max, min = 0) => {
I think we can export this into a separate util that we an use throughout the entire app.
Please create a `src/utils.js` file and move this there.
Also let's add tests for it.

2023-08-20 15:34 UTC, edustipend-root commented on src/App.js
> +  const { notifyLoading } = useContext(ModalContext);
Can we rename this to `isLoading` so we stay consistent?

2023-08-20 15:34 UTC, edustipend-root commented on src/App.js
> +      {notifyLoading && (
Can't we rewrite this logic so we don't have to render the modal twice?

So something like

```
 <NotifyModal>
   { isLoading ? <LoadingMessage size='large' /> : <NotifyMe /> }
 </NotifyModal>
```

2023-08-20 15:34 UTC, edustipend-root commented on src/components/Button/styles.css
> -.disabled .edustipend-button {
Why are we removing this?
We want to keep the button disabled when it's the loading state no?

2023-08-20 16:08 UTC, Ezeh20 commented on src/components/LoadingMessage/internals/constants.js
> +export const randomMessage = (array, max, min = 0) => {
Will do

2023-08-20 16:09 UTC, Ezeh20 commented on src/App.js
> +  const { notifyLoading } = useContext(ModalContext);
Alright

2023-08-20 16:12 UTC, Ezeh20 commented on src/App.js
> +      {notifyLoading && (
Tried that, didn't work. The NotifyModal is global so it always pops up, i just made a separate modal for it using the same styles

2023-08-20 16:13 UTC, Ezeh20 commented on src/components/Button/styles.css
> -.disabled .edustipend-button {
The button can still be disabled, that style is not needed

2023-08-20 20:36 UTC, Ezeh20 commented on src/App.js
> +      {notifyLoading && (
Cleaned it up a little

2023-08-22 11:27 UTC, edustipend-root approved these changes
Thanks for making the changes @Ezeh20, looks good for now.
Can you confirm your VS code format settings? Your PRs seem to have a lot of formatting changes.

2023-08-22 11:27 UTC, merged