Feature/beneficiaries component - Fix
edustipend/dotorg pull request #8
Opened 2023-07-07 15:51 UTC by misspelz

2023-07-12 14:08 UTC, misspelz commented
New changes to all sections have been pushed to this feature

2023-07-12 23:12 UTC, misspelz commented
Please, review

2023-07-15 13:30 UTC, edustipend-root requested changes
Hello @misspelz, the changes look good for the most part.
I've added some comments.
Also have you gotten design and product approval on these?

2023-07-15 13:30 UTC, edustipend-root commented on src/assets/achieve.png
Is there a reason why we have the `.png` version and the `.svg` version? Let's delete this and use just the `.svg`

2023-07-15 13:30 UTC, edustipend-root commented on package-lock.json
Please delete this file. We are using `yarn` for managing the dependencies for this project not `npm`.

2023-07-15 13:30 UTC, edustipend-root commented on src/assets/man-in-glasses.jpg
We need to add a task for reducing the size of these images. 4.43MB is too large.
If we are not using this image anywhere in the codebase, we should delete it.

2023-07-15 13:30 UTC, edustipend-root commented on src/assets/numberGrid2.png
Why do we have this asset? Where are we using it? @misspelz

2023-07-15 13:30 UTC, edustipend-root commented on src/assets/smilingman.jpg
@misspelz, please create a task on the [Front-end](https://trello.com/b/oFXtYTOO/front-end) board for reducing the image sizes.

2023-07-15 13:30 UTC, edustipend-root commented on src/assets/womansmiles.jpg
Please refer to my comment about the images. These images are quite large and I worry that it will increase the size of our bundle.

2023-07-15 13:30 UTC, edustipend-root commented on src/sections/Beneficiaries/__tests__/Beneficiaries.test.js
> +    // Test the presence of a header element
Is there a reason we are commenting out this test?

2023-07-15 13:30 UTC, edustipend-root commented on src/sections/HowItWorks/Howitworks.jsx
> +  const howitworks = [
Can we move this into a `constants.js` file since this data is static.

2023-07-15 13:30 UTC, edustipend-root commented on src/sections/HowItWorks/constants.js
> +  headerText: 'How it Works',
Can we make this all upper-case like `'HEADER_TEXT'` so that we can refer to this as `TestId.HEADER_TEXT`.
The convention we want to follow is that our constants be upper-case.

2023-07-15 13:30 UTC, edustipend-root commented on src/sections/HowItWorks/constants.js
> +  rrrrCards: 'rrrr-card',
Same here let's make this `RRR_CARDS`, so we can call `TestId.RRR_CARDS`

2023-07-15 13:30 UTC, edustipend-root commented on src/sections/HowItWorks/internals/RRRRCard.jsx
> +      <div className="RRRR-Card">
Can we make our class names all lower-case? `rrrr-card` instead of `RRRR-Card`

2023-07-15 13:30 UTC, edustipend-root commented on src/sections/HowItWorks/styles.css
> +.RRRR-SVG-header {
Please make the class names all lower-case

2023-07-15 13:30 UTC, edustipend-root commented on src/sections/TakeOffBurden/constant.js
> +  TAKEOFFBURDEN_CONTAINER_TEST_ID: 'takeoffburden-container',
This is good.

2023-07-15 14:09 UTC, misspelz commented on package.json
> +    "install": "^0.13.0",
I have removed it now

2023-07-15 14:10 UTC, misspelz commented on src/assets/achieve.png
I noticed the svgs are larger than the pngs from the design. What do you think?

2023-07-15 14:10 UTC, misspelz commented on package-lock.json
I have deleted it now

2023-07-15 14:11 UTC, misspelz commented on src/assets/man-in-glasses.jpg
I will delete it and any other as well

2023-07-15 14:32 UTC, misspelz commented on src/assets/numberGrid2.png
I have removed it

2023-07-15 14:35 UTC, misspelz commented on src/sections/HowItWorks/Howitworks.jsx
> +  const howitworks = [
Done

2023-07-15 14:38 UTC, misspelz commented on src/sections/HowItWorks/constants.js
> +  headerText: 'How it Works',
Done

2023-07-15 14:38 UTC, misspelz commented on src/sections/HowItWorks/constants.js
> +  rrrrCards: 'rrrr-card',
Done

2023-07-15 14:55 UTC, misspelz commented on src/sections/HowItWorks/internals/RRRRCard.jsx
> +      <div className="RRRR-Card">
Done

2023-07-15 14:55 UTC, misspelz commented on src/sections/HowItWorks/styles.css
> +.RRRR-SVG-header {
Done

2023-07-15 14:55 UTC, misspelz commented on src/sections/TakeOffBurden/constant.js
> +  TAKEOFFBURDEN_CONTAINER_TEST_ID: 'takeoffburden-container',
Thank you, sir

2023-07-15 15:00 UTC, misspelz commented on src/sections/Beneficiaries/__tests__/Beneficiaries.test.js
> +    // Test the presence of a header element
For a reason I can't figure out, it wasn't passing the test

2023-07-15 15:21 UTC, misspelz commented on src/assets/smilingman.jpg
Okay

2023-07-15 22:32 UTC, misspelz commented
I have made the necessary changes based on your feedback. For some images, png was used because it's kb compared to svg which is mb.

2023-07-18 04:40 UTC, edustipend-root commented
@misspelz, I've fixed the tests that caused the build to fail.
Merging this PR now to unblock the remaining work for this.

2023-07-18 04:40 UTC, edustipend-root approved these changes

2023-07-18 04:41 UTC, merged